export type UserDTO = {
  user_id: string;
  email: string;
  password: string;
  name: string;
  telephone: string;
  monthly_income: number;
  cpf: string;
  birth_date: string;
  hashed_signature: string | null;
  photo: string | null;
  iptu: number | null;
  street: string | null;
  neighborhood: string | null;
  number: string | null;
  zip_code: string | null;
  city: string | null;
  state: string | null;
  marital_status: string | null;
  profession: string | null;
};
